### ISSUE TITLE
Notifier crash version 1.0.6

### ISSUE THREAD

**Issue by lucasxdavii** [VeroxCode/Guardian-AntiCheat#5]
Error: "Call to a member function hasNotifications() on null" (EXCEPTION) in "plugins/Guardian-AntiCheat/src/veroxcode/Guardian/Checks/Notifier" at line 82

**Comment by VeroxCode** [comment]
I need the full error log.

**Comment by NdaruAjaa** [comment]
PocketMine-MP version: 5.6.1+dev [Protocol 618]
Git commit: b37a59e25060553bcd237dca5d645cb945314863
PHP version: 8.1.23
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: AntiCheat

Thread: Main
Error: Call to a member function hasNotifications() on null
File: plugins/AntiCheat/src/veroxcode/Guardian/Checks/Notifier
Line: 82
Type: Error
Backtrace:
#0 plugins/AntiCheat/src/veroxcode/Guardian/Checks/Notifier(30): veroxcode\Guardian\Checks\Notifier::NotifyPlayers(string[10] Skek t rex, object veroxcode\Guardian\User\User#342804, object veroxcode\Guardian\Checks\Movement\Timer#43834)
#1 plugins/AntiCheat/src/veroxcode/Guardian/Checks/Movement/Timer(36): veroxcode\Guardian\Checks\Notifier::NotifyFlag(string[10] Skek t rex, object veroxcode\Guardian\User\User#342804, object veroxcode\Guardian\Checks\Movement\Timer#43834, int 3, true)
#2 plugins/AntiCheat/src/veroxcode/Guardian/Listener/EventListener(68): veroxcode\Guardian\Checks\Movement\Timer->onMove(object pocketmine\player\Player#358365, object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#428369, object veroxcode\Guardian\User\User#342804)
#3 pmsrc/src/event/RegisteredListener(61): veroxcode\Guardian\Listener\EventListener->onPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#314259)
#4 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#314259)
#5 pmsrc/src/network/mcpe/NetworkSession(487): pocketmine\event\Event->call()
#6 pmsrc/src/network/mcpe/NetworkSession(433): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#428369, string[63] ..x:.A.!$C.z.Cr=.B.6.C.........!$C............9....n.T;........)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[53] ...Xa...EQ..Q.R.".V..f.....$.......0..sc.....{..B.a..)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 12, string[62] .f..A...N..e.`....]D.e.....d.y...l.za.O....0.h0...{...L.+...E.)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#6795)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1707): pocketmine\snooze\SleeperHandler->sleepUntil(float 1696736328.6144)
#14 pmsrc/src/Server(1089): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#5, object pocketmine\utils\MainLogger#4, string[16] /home/container/, string[24] /home/container/plugins/)
#16 pmsrc/src/PocketMine(357): pocketmine\server()
#17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by NdaruAjaa** [comment]
PocketMine-MP version: 5.6.1+dev [Protocol 618]
Git commit: b37a59e25060553bcd237dca5d645cb945314863
PHP version: 8.1.23
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Guardian-AntiCheat

Thread: Main
Error: Call to a member function hasNotifications() on null
File: plugins/Guardian-AntiCheat/src/veroxcode/Guardian/Checks/Notifier
Line: 82
Type: Error
Backtrace:
#0 plugins/Guardian-AntiCheat/src/veroxcode/Guardian/Checks/Notifier(30): veroxcode\Guardian\Checks\Notifier::NotifyPlayers(string[10] Skek t rex, object veroxcode\Guardian\User\User#342804, object veroxcode\Guardian\Checks\Movement\Timer#43834)
#1 plugins/Guardian-AntiCheat/src/veroxcode/Guardian/Checks/Movement/Timer(36): veroxcode\Guardian\Checks\Notifier::NotifyFlag(string[10] Skek t rex, object veroxcode\Guardian\User\User#342804, object veroxcode\Guardian\Checks\Movement\Timer#43834, int 3, true)
#2 plugins/Guardian-AntiCheat/src/veroxcode/Guardian/Listener/EventListener(68): veroxcode\Guardian\Checks\Movement\Timer->onMove(object pocketmine\player\Player#358365, object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#428369, object veroxcode\Guardian\User\User#342804)
#3 pmsrc/src/event/RegisteredListener(61): veroxcode\Guardian\Listener\EventListener->onPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#314259)
#4 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#314259)
#5 pmsrc/src/network/mcpe/NetworkSession(487): pocketmine\event\Event->call()
#6 pmsrc/src/network/mcpe/NetworkSession(433): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#428369, string[63] ..x:.A.!$C.z.Cr=.B.6.C.........!$C............9....n.T;........)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[53] ...Xa...EQ..Q.R.".V..f.....$.......0..sc.....{..B.a..)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 12, string[62] .f..A...N..e.`....]D.e.....d.y...l.za.O....0.h0...{...L.+...E.)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#6795)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1707): pocketmine\snooze\SleeperHandler->sleepUntil(float 1696736328.6144)
#14 pmsrc/src/Server(1089): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#5, object pocketmine\utils\MainLogger#4, string[16] /home/container/, string[24] /home/container/plugins/)
#16 pmsrc/src/PocketMine(357): pocketmine\server()
#17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by lucasxdavii** [comment]
Code:
[88]         $message = substr_replace($message, $prefix, $msgPrefixPos, 8);
[89]         $msgPlayerPos = strpos($message, "%PLAYER%");
[90]         $message = substr_replace($message, $name, $msgPlayerPos,8);
[91]         $msgCheckPos = strpos($message, "%CHECK%");
[92]         $message = substr_replace($message, $Check->getName(), $msgCheckPos, 7);
[93] 
[94]         foreach (Guardian::getInstance()->getServer()->getOnlinePlayers() as $player){
[95] 
[96]             $notifyUser = Guardian::getInstance()->getUserManager()->getUser($player->getUniqueId()->toString());
[97]             $hasNotifications = $notifyUser->hasNotifications();
[98] 
[99]             if ($player->hasPermission("guardian.notify")){
[100]                 if ($hasNotifications){
[101]                     $player->sendMessage($message);
[102]                 }
[103]             }
[104]         }
[105]         $user->resetAlertCount($Check->getName());
[106]     }
[107]

**Comment by NdaruAjaa** [comment]
Is that the code to fix?

**Comment by VeroxCode** [comment]
Is your config file up to date? It might be that you're missing a notification setting in the config

**Comment by NdaruAjaa** [comment]
I use Guardian Anticheat's built-in config.yml

**Comment by VeroxCode** [comment]
the config doesn't update itself with missing keys yet.

**Comment by xqwtxon** [comment]
> the config doesn't update itself with missing keys yet.

You should verify these configuration are up to date inside of the plugin by using `config-version` detect from the data folder if match on plugin resources.

**Comment by xqwtxon** [comment]
Also 
```php
// Not necessary since PocketMine creates
// data folder correctly.
@mkdir($this->getDataFolder());
		
// Also this
$this->saveDefaultConfig();
// This is on plugin phar:// resources.
$this->getResource("config.yml");
```

**Comment by VeroxCode** [comment]
The Plugin warns you if your config is outdated. And the code provided creates the path and saves the default config if it doesn't exist
